#!/usr/bin/env bash

# VERSION : 1.1

SIZE_CONTEXT=50

usage() {
cat <<EOF
Name: mans
Description: This script outputs a command description or an option description from the man page.
Usage:
	mans wget -b : Show wget -b option description
	mans ls: Show the ls command description
EOF
}

if (( $# == 0 ))
then
	usage
	exit 1
fi

PROG="$1"

if ! man "${PROG}" > /dev/null 2>&1
then
	echo "unknown man page: ${PROG}" >&2
	exit 2
fi

if (( $# == 2 ))
then
	OPT="$2"
	MANROFFOPT='-c' man "${PROG}" 2> /dev/null | col -bx | sed -n "/^ *${OPT}/,/^$/p" | grep --color=always -A"${SIZE_CONTEXT}" -e "^ *${OPT}" -e "^ *${OPT},.*" -e "^ *-.*, ${OPT}" | sed -En '/^$/q;p'
else
	MANROFFOPT='-c' man "${PROG}" 2> /dev/null | col -bx | sed -n "/^DESCRIPTION/,/^$/p"
fi

exit 0
